default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: proyectoprueba_test

production:
  <<: *default
  database: proyectoprueba_production
  username: proyectoprueba
  password: <%= ENV['PROYECTOPRUEBA_DATABASE_PASSWORD'] %>